services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - fastapi-network
  
  db:
    image: postgres:14.3-alpine3.16
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - fastapi-network
  
volumes:
  postgres_db_data:

networks:
  fastapi-network:
    driver: bridge
